
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.django  # Указываем путь к Dockerfile для Django
    container_name: django_app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app_network  # Подключаем к общей сети

  redis:
    image: redis:7.2
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network  # Подключаем к общей сети

networks:
  app_network:
    external: true